interface=eth1
# interface=eth2 # se serve su più interfacce, poi si devono taggare le direttive come da esempi seguenti

# nota: il range è lo spazio di indirizzi allocabili,
# ma anche se più ridotto fa parte comunque della subnet
# quindi visto che la rete è 10.99.0.0/16 la mask deve essere 255.255.0.0
dhcp-range=eth1,10.99.1.0,10.99.1.255,255.255.0.0,12h

dhcp-option=3

dhcp-option=eth1,121,172.22.0.0/28,10.99.0.1
