agentAddress udp:161
view all included .1
rocommunity public default -V all
rwcommunity supercom default -V all

# query:
# snmpget -v 1 -c public $IP NET-SNMP-EXTEND-MIB::nsExtendOutputFull.\"test\"
extend-sh check_status /usr/bin/systemctl status slapd > /dev/null && /sbin/ip a | /usr/bin/grep -Ewq '172\.22\.0\.10' && echo ACTIVE

# builtin vari: load, disk, proc, tutto il UCD-SNMP-MIB...
