agentAddress udp:161
view all included .1
rocommunity public default -V all
rwcommunity supercom default -V all

extend-sh comandi /bin/ls -1 /usr/local/bin
extend-sh authkeys /usr/bin/sudo -s eval ls -l /home/\*/.ssh/authorized_keys
