# nota: questi task funzionano correttamente solo se ldap è già ben configurato su tutti gli host
# altrimenti non esistono l'utente exam e il gruppo demo; potrebbe essere necessario ripetere il provisioning
---
- name: Create home and keys dir on server
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
    owner: root # dovrebbe essere exam
    group: root # dovrebbe essere demo
  loop:
    - /home/exam
    - /home/exam/.ssh

- name: Copy keys to authorize
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/exam/.ssh/authorized_keys
    owner: root # dovrebbe essere exam
    group: root # dovrebbe essere demo
    mode: "0600"
  loop:
    - id_demo.pub

- name: Configure sudo to ls .ssh dirs
  ansible.builtin.copy:
    src: sudols
    dest: /etc/sudoers.d/sudols
    validate: /usr/sbin/visudo -csf %s
